### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by emidoots** [hexops/sycl24#1]
# Schedule preparation

Total time: 6 hours

* Morning
  * 30 minutes for people to get settled, get software installed
  * 2 hours of run-through / intense learning in the morning
* Long/casual lunch break 12:00pm - 2:30pm (tell people 2:15pm so they are back early?)
* Afternoon
  * 2 hours - learning time
  * 1.5 hours - wrap up time, let people chat, work with people on their code/projects

TODO:

* [ ] Where during the day to hand out pins/stickers
* [ ] Flesh out outline in slides further

# Google drive preparation

* [ ] `zig/` has binaries and source tarballs of the exact Zig version used from https://machengine.org/about/nominated-zig/#202430-mach
* [ ] `zls/` has binaries and source tarballs of the exact ZLS version to be used
* [ ] `pixi/` has binaries and source tarballs of Pixi built for every platform
  * [ ] TODO: should build with both sysgpu and dawn just to be safe? in case one doesn't run for someone
* [ ] `audio/` has premade sfx and bgm people can use for their own games

# Google slides preparation

https://docs.google.com/presentation/d/1DxjcDqrm52-cfqM5M2pbABeGVuQKlW0FUUUtoFvAZfw/edit?usp=sharing

Slide high-level goals:

* [ ] Introduction to modern graphics APIs
* [ ] What shaders are and how to work with them
* [ ] 2D sprite rendering
* [ ] Audio rendering
* [ ] Working with an entity component system
* [ ] Connecting the pieces together

# SYCL24 repository preparation

https://github.com/hexops/sycl24

* [ ] README
  * [ ] Cool screenshot
  * [ ] Link to Google drive
  * [ ] Link to Google slides
* [ ] The Game
  * [ ] Inspiration: my favorite game, [Kingdom New Lands](https://www.youtube.com/watch?v=HaKjzu7_eF0) - basics:
    * 2D side-scroller
    * Day/night cycle, during the day you build your town during the night you defend against monsters
    * You play as the king
    * Villagers spawn over time, you can pay them to be your subjects
    * You can collect coins (taxes) from villagers
    * You can spend coins on upgrading villagers and buildings in your town
    * Goal of the game: avoid monsters getting into your town and destroying everything (tower-defence style)
* [ ] Artwork basics
  * [x] Integrate Ziguanas somehow? Could the king or the king's subjects be Ziguanas?
  * [ ] 'King' / main player, animations (doesn't have to be on a horse, could look like a knight or something):
    * [ ] Walking animation
    * [ ] Sword/attack animation
  * [ ] King's peasant subject, animations:
    * [ ] Walking animation
    * [ ] Being attacked animation (so peasants can die if not upgraded to knights)
  * [ ] King's knight, animations:
    * [ ] Walking animation
    * [ ] Attacking an enemy
  * [ ] One or two buildings, e.g. 'central building of the town' made of wood/straw or something. Maybe a farm sprite which could just spawn coins periodically?
  * [ ] Enemies
    * [ ] Make the enemies a bit funny? Rustaceans? Or have them be 'corrupted memory'?
  * [ ] Environment
    * [ ] Trees
    * [ ] Ground / grass
    * [x] Water
    * [x] Rain sprite?
* [ ] Code ideas
  * [x] https://github.com/hexops/mach/issues/1183
  * [x] ecs: https://github.com/hexops/mach/issues/1178
  * [x] ECS audio module
  * [x] Text rendering
  * [ ] Sprite animation
  * [ ] basic 2D collision/physics - just really simple sprite collision logic. May be able to reuse some of the work in https://github.com/hexops/mach/pull/1158
  * [ ] LDTK level loading - is there any integration with pixi here that is reasonable?
  * [ ] ECS module for sprite rendering pixi sprites - basically take https://github.com/hexops/mach/tree/main/examples/sprite + the information foxxne DM'd me to see if we can render pixi sprites in a reasonable way
  * [ ] Starter ECS module for zig-imgui - basically take https://github.com/hexops/mach/tree/main/examples/core-custom-entrypoint and create a module like Game.zig that does setup/rendering of imgui so you can use it easily.
  * [x] sysaudio ECS module - basically take https://github.com/hexops/mach/tree/main/examples/core-custom-entrypoint and create a module like Game.zig that uses sysaudio to play background music and sound effects at different volumes. Can reuse some of the work in https://github.com/hexops/mach/pull/1138

# SYCL24-assets repository preparation

Prepare a bunch of pre-made things people can use to make their own game during the workshop

* [ ] Premade levels?
* [ ] Premade sprites for different game types (kenney.nl?)
* [x] Premade music
  * [ ] Export 'quicksounds' fl studio work (1h of work)
  * [ ] Create atmospheric sounds with builtin fl studio instruments
  * [ ] Find atmospheric rain, etc. bgm

# Meta / social aspects

* [x] Confirm with Loris # of people and general idea of who is coming
* [ ] Ideally get people to run a basic hardware check before hand
  * [ ] sysaudio works on their machine
  * [ ] sprite rendering works on their machine
  * [ ] pixi works on their machine

# Finishing touches

* [ ] Flash drives are loaded with everything:
  * [ ] Copies of https://github.com/hexops/sycl24-assets
  * [ ] Copies of https://github.com/hexops/sycl24
  * [ ] Copies of Google Drive
  * [ ] Copies of Google Slides
  * [ ] Can I download Zig cache/dependencies for every OS/arch just in case?
* [ ] Everything is packed / ready to go
  * [ ] Flash drives
  * [ ] Pins to hand out
  * [ ] Stickers to hand out
  * [ ] Spare headphones to hand out
  * [ ] Spare US-EU power adapters
  * [ ] Spare laptop in case someone has issues?
